version: '3'
services:
    sadako-bot:
        container_name: sadako-bot
        restart: always
        build: .
    mongo:
        container_name: mongo
        image: mongo
        ports:
            ['27017:27017']